# Generated by Django 4.2.7 on 2023-12-27 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='balance_after_transactions',
            new_name='balance_after_transaction',
        ),
    ]
