# Generated by Django 4.2.7 on 2023-12-30 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_rename_balance_after_transactions_transaction_balance_after_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='receiver_account_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.IntegerField(choices=[(1, 'Deposite'), (2, 'Withdrawal'), (3, 'Loan'), (4, 'Loan Paid'), (5, 'TRANSFER')]),
        ),
    ]
